### ISSUE TITLE
For the past few days, this plugin has become very laggy, especially when hovering over the 'Community' or 'Store' tabs in the Steam library interface.

### ISSUE THREAD

**Issue by xiaohuaihai** [yurisuika/Zehn#43]
For the past few days, this plugin has become very laggy, especially when hovering over the 'Community' or 'Store' tabs in the Steam library interface.

**Comment by chromczyt** [comment]
same think, i update millennium and this this does not work properly... like i try scroll in game activity and whole UI just bug in self together

**Comment by xiaohuaihai** [comment]
I have tried, laggy as before, and the change of the theme cant be saved. Other theme cant do this experiment with they don't have a such config to custom.

**Comment by yurisuika** [comment]
Well that issue isn't concerning the lag, but rather why the settings aren't changing for you.

Given your issue concerns the dropdown menus on the navbar, you may be encountering something related to this issue. https://github.com/shdwmtr/millennium/issues/266

If you are still having it after that is resolved, I suppose if you can narrow down which commit this started occurring under we may find a possible solution.

**Comment by xiaohuaihai** [comment]
Maybe related it. I will repeat the appearance of this issue for better understanding and solving with AI translator.
Starting from when the theme configuration interface was changed from one version to multiple separated tabs, I accidentally discovered that clicking into the "Library" interface would cause lag throughout Steam, but switching back to the "Store" would resolve it. Later, I tried modifying theme configurations but found that no matter how I adjusted the settings, after restarting Steam, the configurations would revert to default.

By the way, I previously asked the author of the "Mill" theme. Due to features like Mill's automatic updates, which invoke cmd commands, Kaspersky would intercept this process upon launching Steam. After clicking "Allow," the login interface would reload automatically once, and only then could I log in by clicking my avatar. This might be a relevant detail.

As mentioned earlier, since the other skins I tested lack a configuration interface, I couldn’t compare whether they also fail to save settings.

**Comment by yurisuika** [comment]
As I mentioned in that issue, in my experimenting the settings toggle switches not working correctly only occurred when a skin has these custom settings categories. That is why you did not experience this before Zehn's settings were all in the default category. However, that should have been fixed as of Millennium 2.18.0. Currently, Millennium is up to 2.21.0, so if you are still having that issue you may want to check if you are on an old version. I can say that I am no longer experiencing this issue.

**Comment by xiaohuaihai** [comment]
I'm sure that its 2.22.0 now for the new display, and the config can be saved. But still have the same problem as before. Maybe my PC is truly poor to running that?

**Comment by yurisuika** [comment]
I think it is safe to say that your issue was related to what broke stuff like the event overlay. When colorzing the throbbers, I forgot a child combinator selector and so any div that had the throbber as a child at some point was being resized to 64x64 px. I was getting some lag when switching to a game page, but more notably the entire sidebar was blank and pushed up into the navbar etc. Those `:has` selectors can give you a nasty bite if you let them have an infinite chain.
